language: go

go:
  - 1.9.x
  - tip

install: true

script:
  - make vendor_get && make build
  - go test -race -coverprofile=converage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t f4a18ac8-7263-40bd-a33d-057bd3e67df8
