swagger: '2.0'
info:
  title: Ease Gateway Administration API
  description: Ease Gateway supports APIs on administration panel.
  version: "1.0"
schemes:
  - http
  - https
basePath: /admin/v1
produces:
  - application/json
paths:
  /plugin-types:
    get:
      summary: Retrieves Plugin Type
      description: |
        The Plugin Type retrieve endpoint returns all available plugin types Gateway supports currently.
        Which can be used to create a plugin instance with a special configuration.
      responses:
        200:
          description: Plugin types response.
          schema:
            $ref: '#/definitions/PluginTypesRetrieveResponse'
        default:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
  /pipeline-types:
    get:
      summary: Retrieves Pipeline Type
      description: |
        The Pipeline Type retrieve endpoint returns all available pipeline types Gateway supports
        currently. Which can be used to create a pipeline instance with a special configuration.
      responses:
        200:
          description: Pipeline types response.
          schema:
            $ref: '#/definitions/PipelineTypesRetrieveResponse'
        default:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
  /plugins:
    post:
      summary: Creates Plugin Instance
      description: |
        The Plugin Instance creation endpoint creates a special plugin instance according to the
        plugin type and the configuration.
      parameters:
        - name: pluginCreationRequest
          in: body
          schema:
            $ref: '#/definitions/PluginCreationRequest'
          required: true
          description: Plugin type and configuration.
      responses:
        400:
          description: |
            Invalid plugin instance creation request parameter. Including, invalid plugin type
            or invalid configuration according to the plugin instance is being created.
          schema:
            $ref: '#/definitions/Error'
        409:
          description: |
            Plugin instance with the given name request parameter provided is already existing.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Plugin instance is created successfully.
    get:
      summary: Retrieves Plugin Instances
      description: |
        The Plugin Instances retrieve endpoint returns all existing plugin instnaces Gateway
        has currently.
      parameters:
        - name: pluginsRetrieveRequest
          in: body
          schema:
            $ref: '#/definitions/PluginsRetrieveRequest'
          required: true
          description: Plugin instance retrieve conditions.
      responses:
        400:
          description: |
            Invalid plugin instance retrieve request parameter. Including, invalid plugin type.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Plugin instance response.
          schema:
            $ref: '#/definitions/PluginsRetrieveResponse'
    put:
      summary: Updates Plugin Instance
      description: |
        The Plugin Instance update endpoint updates a special plugin instance according to the
        plugin type and the configuration.
      parameters:
        - name: pluginUpdateRequest
          in: body
          schema:
            $ref: '#/definitions/PluginUpdateRequest'
      responses:
        400:
          description: |
            Invalid plugin instance udpate request parameter. Including, invalid plugin type
            or invalid configuration according to the plugin instance is being updated.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Plugin instnace not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Plugin instance is updated successfully.
  /plugins/{pluginName}:
    get:
      summary: Retrieves Plugin Instance
      description: |
        The Plugin Instance retrieve endpoint returns an existing plugin instnace Gateway has
        currently by plugin name.
      parameters:
        - name: pluginName
          in: path
          description: Plugin instance name to retrieve.
          required: true
          type: string
      responses:
        400:
          description: Invalid plugin instance name to retrieve.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Plugin instnace not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Plugin instnace response.
          schema:
            $ref: '#/definitions/PluginSpec'
    delete:
      summary: Deletes Plugin Instance
      description: |
        The Plugin Instance deletion endpoint deletes an existing plugin instnace Gateway has
        currently by plugin name.
      parameters:
        - name: pluginName
          in: path
          description: Plugin instance name to delete.
          required: true
          type: string
      responses:
        400:
          description: Invalid plugin instance name to delete.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Plugin instnace not found by given name.
          schema:
            $ref: '#/definitions/Error'
        406:
          description: |
            Plugin instnace could not be deleted by given name since it is used by
            one or more pipelines.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Plugin instance is deleted successfully.
  /pipelines:
    post:
      summary: Creates Pipwline Instance
      description: |
        The Pipeline Instance creation endpoint creates a special pipeline instance according
        to the pipeline type and the configuration.
      parameters:
        - name: pipelineCreationRequest
          in: body
          schema:
            $ref: '#/definitions/PipelineCreationRequest'
          required: true
          description: Pipeline type and configuration.
      responses:
        400:
          description: |
            Invalid pipeline instance creation request parameter. Including, invalid pipeline
            type or invalid configuration according to the pipeline instance is being created,
            or one or more plugin instances in the pipeline are not found.
          schema:
            $ref: '#/definitions/Error'
        409:
          description: |
            Pipeline instance with the given name request parameter provided is already existing.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Pipeline instance is created successfully.
    get:
      summary: Retrieves Pipeline Instances
      description: |
        The Pipeline Instances retrieve endpoint returns all existing pipeline instnaces Gateway
        has currently.
      parameters:
        - name: pipelinesRetrieveRequest
          in: body
          schema:
            $ref: '#/definitions/PipelinesRetrieveRequest'
          required: true
          description: Pipeline instance retrieve conditions.
      responses:
        400:
          description: |
            Invalid pipeline instance retrieve request parameter. Including, invalid pipeline type.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Pipeline instances response.
          schema:
            $ref: '#/definitions/PipelinesRetrieveResponse'
    put:
      summary: Updates Pipeline Instance
      description: |
        The Pipeline Instance update endpoint updates a special pipeline instance according to the
        pipeline type and the configuration.
      parameters:
        - name: pipelineUpdateRequest
          in: body
          schema:
            $ref: '#/definitions/PipelineUpdateRequest'
      responses:
        400:
          description: |
            Invalid pipeline instance udpate request parameter. Including, invalid pipeline type
            or invalid configuration according to the pipeline instance is being updated.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: |
            Pipeline instnace not found by given name, or one or more plugin instances in the
            pipeline are not found.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Pipeline instance is updated successfully.
  /pipelines/{pipelineName}:
    get:
      summary: Retrieves Pipeline Instance
      description: |
        The Pipeline Instance retrieve endpoint returns an existing pipeline instnace Gateway has
        currently by pipeline name.
      parameters:
        - name: pipelineName
          in: path
          description: Pipeline instance name to retrieve.
          required: true
          type: string
      responses:
        400:
          description: Invalid pipeline instance name to retrieve.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Pipeline instnace not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Pipeline instnace response.
          schema:
            $ref: '#/definitions/PipelineSpec'
    delete:
      summary: Deletes Pipeline Instance
      description: |
        The Pipeline Instance deletion endpoint deletes an existing pipeline instnace Gateway has
        currently by pipeline name.
      parameters:
        - name: pipelineName
          in: path
          description: Pipeline instance name to delete.
          required: true
          type: string
      responses:
        400:
          description: Invalid pipeline instance name to delete.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Pipeline instnace not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: Pipeline instance is deleted successfully.
definitions:
  PluginTypesRetrieveResponse:
    type: object
    required:
      - plugin_types
    properties:
      plugin_types:
        type: array
        items:
          type: string
  PipelineTypesRetrieveResponse:
    type: object
    required:
      - pipeline_types
    properties:
      pipeline_types:
        type: array
        items:
          type: string
  PluginCreationRequest:
    type: object
    required:
      - type
      - config
    properties:
      type:
        type: string
        description: One valid type of available plugin types listed in PluginTypesRetrieveResponse.
      config:
        type: object
        description: |
          A special configuration object of the plugin type. Check Plugin Reference document for
          more information.
  PluginsRetrieveRequest:
    type: object
    properties:
      name_pattern:
        type: string
        description: Plugin name filter condition, supports regex expression.
      types:
        type: array
        items:
          type: string
        description: Plugin types filter condition, supports regex expression.
  PluginsRetrieveResponse:
    type: object
    required:
      - plugins
    properties:
      plugins:
        type: array
        items:
          $ref: '#/definitions/PluginSpec'
  PluginUpdateRequest:
    type: object
    required:
      - type
      - config
    properties:
      type:
        type: string
        description: One valid type of available plugin types listed in PluginTypesRetrieveResponse.
      config:
        type: object
        description: |
          A special configuration object of the plugin type. Check Plugin Reference document
          for more information.
  PluginSpec:
    type: object
    required:
      - type
      - config
    properties:
      type:
        type: string
        description: One valid type of available plugin types listed in PluginTypesRetrieveResponse.
      config:
        type: object
        description: |
          A special configuration object of the plugin type. Check Plugin Reference document for
          more information.
  PipelineCreationRequest:
    type: object
    required:
      - type
      - config
    properties:
      type:
        type: string
        description: One valid type of available pipeline types listed in PipelineTypesRetrieveResponse.
      config:
        type: object
        description: |
          A special configuration object of the pipeline type. Check Pipeline Reference document for
          more information.
  PipelinesRetrieveRequest:
    type: object
    properties:
      name_pattern:
        type: string
        description: Pipeline name filter condition, supports regex expression.
      types:
        type: array
        items:
          type: string
        description: Pipeline types filter condition, supports regex expression.
  PipelinesRetrieveResponse:
    type: object
    required:
      - pipelines
    properties:
      pipelines:
        type: array
        items:
          $ref: '#/definitions/PipelineSpec'
  PipelineUpdateRequest:
    type: object
    required:
      - type
      - config
    properties:
      type:
        type: string
        description: One valid type of available pipeline types listed in PipelineTypesRetrieveResponse.
      config:
        type: object
        description: |
          A special configuration object of the pipeline type. Check Pipeline Reference document
          for more information.
  PipelineSpec:
    type: object
    required:
      - type
      - config
    properties:
      type:
        type: string
        description: One valid type of available pipeline types listed in PipelineTypesRetrieveResponse.
      config:
        type: object
        description: |
          A special configuration object of the pipeline type. Check Pipeline Reference document
          for more information.
  Error:
    type: object
    required:
      - Error
    properties:
      Error:
        type: string
