swagger: '2.0'
info:
  title: Ease Gateway Health API
  description: Ease Gateway supports APIs for health check.
  version: "1.0"
schemes:
  - http
  - https
basePath: /health/v1
produces:
  - application/json
paths:
  /check:
    get:
      summary: Checks Gateway Service Instance Existing
      description: |
        The Gateway Service Instance Health check endpoint returns a http status code
        to present if the gateway service instance is existing and runs normally.
      responses:
        200:
          description: |
            The gateway service instance which serves API request currently
            is existing and runs normally.
        default:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
  /info:
    get:
      summary: Retriev Gateway Service Information
      description: |
        The Gateway Service Instance Health infomation endpoint returns build
        information of gateway service instance.
      responses:
        200:
          description: |
            The information of the gateway service instance
            which serves API request currently.
          schema:
            $ref: '#/definitions/HealthInfoResponse'
        default:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
definitions:
  HealthInfoResponse:
    type: object
    required:
      - build
    properties:
      build:
        type: object
        required:
          - name
          - release
          - build
          - repository
        properties:
          name:
            type: string
          release:
            type: string
          build:
            type: string
          repository:
            type: string
  Error:
    type: object
    required:
      - Error
    properties:
      Error:
        type: string
