swagger: '2.0'
info:
  title: Ease Gateway Statistics API
  description: Ease Gateway supports APIs for statistics.
  version: "1.0"
schemes:
  - http
  - https
basePath: /statistics/v1
produces:
  - application/json
paths:
  /pipelines/{pipelineName}/plugins/{pluginName}/indicators:
    get:
      summary: Retrieves Plugin Statistics Indicator Names
      description: |
        The Plugin Statistics Indicators retrieve endpoint returns the name list of all available
        statistics indicators plugin instance exposed against the pipleine instance.
      parameters:
        - name: pipelineName
          in: path
          description: Pipeline instance name to query.
          required: true
          type: string
        - name: pluginName
          in: path
          description: Plugin instance name to query.
          required: true
          type: string
      responses:
        400:
          description: Invalid pipeline or plugin instance name to query.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: The statistics of pipeline instnace not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: The names of statistics indicator.
          schema:
            $ref: '#/definitions/PluginIndicatorNames'
  /pipelines/{pipelineName}/plugins/{pluginName}/indicators/{indicatorName}/value:
    get:
      summary: Retrieves Plugin Statistics Indicator Value
      description: |
        The Plugin Statistics Indicator Value retrieve endpoint returns the value of given statistics
        indicator plugin instance exposed against the pipleine instance.
      parameters:
        - name: pipelineName
          in: path
          description: Pipeline instance name to query.
          required: true
          type: string
        - name: pluginName
          in: path
          description: Plugin instance name to query.
          required: true
          type: string
        - name: indicatorName
          in: path
          description: Statistics indicator name to query.
          required: true
          type: string
      responses:
        400:
          description: Invalid pipeline, plugin instance name or indicator name to query.
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Failed to query value from plugin indicator.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: The statistics of pipeline instnace or indicator not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: The value of statistics indicator.
          schema:
            $ref: '#/definitions/PluginIndicatorValue'
  /pipelines/{pipelineName}/plugins/{pluginName}/indicators/{indicatorName}/desc:
    get:
      summary: Retrieves Plugin Statistics Indicator Description
      description: |
        The Plugin Statistics Indicator Description retrieve endpoint returns the description
        of given statistics indicator plugin instance exposed against the pipleine instance.
      parameters:
        - name: pipelineName
          in: path
          description: Pipeline instance name to query.
          required: true
          type: string
        - name: pluginName
          in: path
          description: Plugin instance name to query.
          required: true
          type: string
        - name: indicatorName
          in: path
          description: Statistics indicator name to query.
          required: true
          type: string
      responses:
        400:
          description: Invalid pipeline, plugin instance name or indicator name to query.
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Failed to describe plugin indicator.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: The statistics of pipeline instnace or indicator not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: The description of statistics indicator.
          schema:
            $ref: '#/definitions/PluginIndicatorDescription'
  /pipelines/{pipelineName}/indicators:
    get:
      summary: Retrieves Pipeline Statistics Indicator Names
      description: |
        The Pipeline Statistics Indicators retrieve endpoint returns the name list of all available
        statistics indicators pipeline instance exposed.
      parameters:
        - name: pipelineName
          in: path
          description: Pipeline instance name to query.
          required: true
          type: string
      responses:
        400:
          description: Invalid pipeline instance name to query.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: The statistics of pipeline instnace not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: The names of statistics indicator.
          schema:
            $ref: '#/definitions/PipelineIndicatorNames'
  /pipelines/{pipelineName}/indicators/{indicatorName}/value:
    get:
      summary: Retrieves Pipeline Statistics Indicator Value
      description: |
        The Pipeline Statistics Indicator Value retrieve endpoint returns the value of given
        statistics indicator pipeline instance exposed.
      parameters:
        - name: pipelineName
          in: path
          description: Pipeline instance name to query.
          required: true
          type: string
        - name: indicatorName
          in: path
          description: Statistics indicator name to query.
          required: true
          type: string
      responses:
        400:
          description: Invalid pipeline instance name or indicator name to query.
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Failed to query value from pipeline indicator.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: The statistics of pipeline instnace or indicator not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: The value of statistics indicator.
          schema:
            $ref: '#/definitions/PipelineIndicatorValue'
  /pipelines/{pipelineName}/indicators/{indicatorName}/desc:
    get:
      summary: Retrieves Pipeline Statistics Indicator Description
      description: |
        The Pipeline Statistics Indicator Description retrieve endpoint returns the description
        of given statistics indicator pipeline instance exposed.
      parameters:
        - name: pipelineName
          in: path
          description: Pipeline instance name to query.
          required: true
          type: string
        - name: indicatorName
          in: path
          description: Statistics indicator name to query.
          required: true
          type: string
      responses:
        400:
          description: Invalid pipeline or indicator name to query.
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Failed to describe pipeline indicator.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: The statistics of pipeline instnace or indicator not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: The description of statistics indicator.
          schema:
            $ref: '#/definitions/PipelineIndicatorDescription'
  /pipelines/{pipelineName}/task/indicators:
    get:
      summary: Retrieves Task Statistics Indicator Names
      description: |
        The Task Statistics Indicators retrieve endpoint returns the name list of all available
        statistics indicators task exposed against the pipleine instance.
      parameters:
        - name: pipelineName
          in: path
          description: Pipeline instance name to query.
          required: true
          type: string
      responses:
        400:
          description: Invalid pipeline instance name to query.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: The statistics of pipeline instnace not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: The names of statistics indicator.
          schema:
            $ref: '#/definitions/TaskIndicatorNames'
  /pipelines/{pipelineName}/task/indicators/{indicatorName}/value:
    get:
      summary: Retrieves Task Statistics Indicator Value
      description: |
        The Task Statistics Indicator Value retrieve endpoint returns the value of given statistics
        indicator task exposed against the pipleine instance.
      parameters:
        - name: pipelineName
          in: path
          description: Pipeline instance name to query.
          required: true
          type: string
        - name: indicatorName
          in: path
          description: Statistics indicator name to query.
          required: true
          type: string
      responses:
        400:
          description: Invalid pipeline instance name or indicator name to query.
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Failed to query value from task indicator.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: The statistics of pipeline instnace or indicator not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: The value of statistics indicator.
          schema:
            $ref: '#/definitions/TaskIndicatorValue'
  /pipelines/{pipelineName}/task/indicators/{indicatorName}/desc:
    get:
      summary: Retrieves Task Statistics Indicator Description
      description: |
        The Task Statistics Indicator Description retrieve endpoint returns the description
        of given statistics indicator task exposed against the pipleine instance.
      parameters:
        - name: pipelineName
          in: path
          description: Pipeline instance name to query.
          required: true
          type: string
        - name: indicatorName
          in: path
          description: Statistics indicator name to query.
          required: true
          type: string
      responses:
        400:
          description: Invalid pipeline instance name or indicator name to query.
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Failed to describe task indicator.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: The statistics of pipeline instnace or indicator not found by given name.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: The statistics indicator description.
          schema:
            $ref: '#/definitions/TaskIndicatorDescription'
  /gateway/uptime:
    get:
      summary: Retrieves Gateway Uptime
      description: |
        The Gateway Uptime retrieve endpoint returns the uptime of the gateway service instance
        in nanosecond unit which serves API request currently.
      responses:
        200:
          description: The uptime of the gateway service instance.
          schema:
            $ref: '#/definitions/UptimeDuration'
  /gateway/rusage:
    get:
      summary: Retrieves Gateway Resource Usage
      description: |
        The Gateway Resource Usage retrieve endpoint returns the OS resource usage consumed by
        the gateway service instance which serves API request currently.
      responses:
        500:
          description: Failed to execute getrusage() syscall.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: The resource usage of the gateway service instance.
          schema:
            $ref: '#/definitions/ResourceUsage'
  /gateway/loadavg:
    get:
      summary: Retrieves Gateway Host Load
      description: |
        The Gateway Host Load retrieve endpoint returns the OS average load hosted
        the gateway service instance which serves API request currently.
      responses:
        403:
          description: Failed to access /proc/loadavg file.
          schema:
            $ref: '#/definitions/Error'
        200:
          description: The host average load on OS level.
          schema:
            $ref: '#/definitions/AvgLoad'
definitions:
  PluginIndicatorNames:
    type: array
    items:
      type: string
# Could be one of:
# - EXECUTION_COUNT_ALL
# - EXECUTION_COUNT_FAILURE
# - EXECUTION_COUNT_SUCCESS
# - EXECUTION_TIME_50_PERCENT_FAILURE
# - EXECUTION_TIME_50_PERCENT_SUCCESS
# - EXECUTION_TIME_90_PERCENT_FAILURE
# - EXECUTION_TIME_90_PERCENT_SUCCESS
# - EXECUTION_TIME_99_PERCENT_FAILURE
# - EXECUTION_TIME_99_PERCENT_SUCCESS
# - EXECUTION_TIME_MAX_ALL
# - EXECUTION_TIME_MAX_FAILURE
# - EXECUTION_TIME_MAX_SUCCESS
# - EXECUTION_TIME_MIN_ALL
# - EXECUTION_TIME_MIN_FAILURE
# - EXECUTION_TIME_MIN_SUCCESS
# - EXECUTION_TIME_STD_DEV_FAILURE
# - EXECUTION_TIME_STD_DEV_SUCCESS
# - EXECUTION_TIME_SUM_ALL
# - EXECUTION_TIME_SUM_FAILURE
# - EXECUTION_TIME_SUM_SUCCESS
# - EXECUTION_TIME_VARIANCE_FAILURE
# - EXECUTION_TIME_VARIANCE_SUCCESS
# - THROUGHPUT_RATE_LAST_15MIN_ALL
# - THROUGHPUT_RATE_LAST_15MIN_FAILURE
# - THROUGHPUT_RATE_LAST_15MIN_SUCCESS
# - THROUGHPUT_RATE_LAST_1MIN_ALL
# - THROUGHPUT_RATE_LAST_1MIN_FAILURE
# - THROUGHPUT_RATE_LAST_1MIN_SUCCESS
# - THROUGHPUT_RATE_LAST_5MIN_ALL
# - THROUGHPUT_RATE_LAST_5MIN_FAILURE
# - THROUGHPUT_RATE_LAST_5MIN_SUCCESS
  PluginIndicatorValue:
    type: object
    description: |
      A special value object of the plugin indicator type. Check Plugin Reference document for
      more information.
  PluginIndicatorDescription:
    type: string
    description: |
      A human readable description of the special plugin indicator type. Check Plugin Reference
      document for more information.
  PipelineIndicatorNames:
    type: array
    items:
      type: string
      enum:
        - EXECUTION_COUNT_ALL
        - EXECUTION_TIME_50_PERCENT_ALL
        - EXECUTION_TIME_90_PERCENT_ALL
        - EXECUTION_TIME_99_PERCENT_ALL
        - EXECUTION_TIME_MAX_ALL
        - EXECUTION_TIME_MIN_ALL
        - EXECUTION_TIME_STD_DEV_ALL
        - EXECUTION_TIME_SUM_ALL
        - EXECUTION_TIME_VARIANCE_ALL
        - THROUGHPUT_RATE_LAST_15MIN_ALL
        - THROUGHPUT_RATE_LAST_1MIN_ALL
        - THROUGHPUT_RATE_LAST_5MIN_ALL
  PipelineIndicatorValue:
    type: object
    description: |
      A special value object of the pipeline indicator type. Check Pipeline Reference document for
      more information.
  PipelineIndicatorDescription:
    type: string
    description: |
      A human readable description of the special plugin indicator type. Check Pipeline Reference
      document for more information.
  TaskIndicatorNames:
    type: array
    items:
      type: string
      enum:
        - EXECUTION_COUNT_ALL
        - EXECUTION_COUNT_FAILURE
        - EXECUTION_COUNT_SUCCESS
  TaskIndicatorValue:
    type: object
    description: |
      A special value object of the pipeline indicator type. Check Pipeline Reference document for
      more information.
  TaskIndicatorDescription:
    type: string
    description: |
      A human readable description of the special task indicator type. Check Pipeline Reference
      document for more information.
  UptimeDuration:
    type: integer
    description: The uptime of the gateway service instance.
  ResourceUsage:
    type: object
    required:
      - Utime
      - Stime
      - Maxrss
      - Ixrss
      - Idrss
      - Isrss
      - Minflt
      - Majflt
      - Nswap
      - Inblock
      - Oublock
      - Msgsnd
      - Msgrcv
      - Nsignals
      - Nvcsw
      - Nivcsw
    properties:
      Utime:
        $ref: '#/definitions/Utime'
      Stime:
        $ref: '#/definitions/Stime'
      Maxrss:
        type: integer
        description: Maximum resident set size.
      Ixrss:
        type: integer
        description: Integral shared memory size.
      Idrss:
        type: integer
        description: Integral unshared data size.
      Isrss:
        type: integer
        description: Integral unshared stack size.
      Minflt:
        type: integer
        description: Page reclaims (soft page faults).
      Majflt:
        type: integer
        description: Page faults (hard page faults).
      Nswap:
        type: integer
        description: Swaps.
      Inblock:
        type: integer
        description: Block input operations.
      Oublock:
        type: integer
        description: Block output operations.
      Msgsnd:
        type: integer
        description: IPC messages sent.
      Msgrcv:
        type: integer
        description: IPC messages received.
      Nsignals:
        type: integer
        description: Signals received.
      Nvcsw:
        type: integer
        description: Voluntary context switches.
      Nivcsw:
        type: integer
        description: Involuntary context switches.
  Utime:
    type: object
    description: User CPU time used.
    required:
      - Sec
      - Usec
    properties:
      Sec:
        type: integer
        description: Duration in second unit.
      Usec:
        type: integer
        description: Duration in microseconds unit.
  Stime:
    type: object
    description: System CPU time used.
    required:
      - Sec
      - Usec
    properties:
      Sec:
        type: integer
        description: Duration in second unit.
      Usec:
        type: integer
        description: Duration in microseconds unit.
  AvgLoad:
    type: object
    required:
      - load1
      - load5
      - load15
    properties:
      load1:
        type: number
        description: CPU and IO utilization of the last one minute periods.
      load5:
        type: number
        description: CPU and IO utilization of the last five minute periods.
      load15:
        type: number
        description: CPU and IO utilization of the last ten minute periods.
  Error:
    type: object
    required:
      - Error
    properties:
      Error:
        type: string
