cluster-name: cluster-A
cluster-role: writer
name: member-001
cluster-client-url: http://localhost:2379
cluster-peer-url: http://localhost:2380
cluster-join-urls: 
api-addr: localhost:2381
data-dir: ./data
cpu-profile-file: ""
memory-profile-file: ""
log-dir: ./logs
debug: true
pipeline-init-parallelism: 1
pipeline-min-parallelism: 5
pipeline-max-parallelism: 5120
plugin-io-data-format-len-limit: 128
plugin-python-root-namespace: false
plugin-shell-root-namespace: false
cgi-dir: ./cgi
cert-dir: ./cert
etcd-request-timeout-in-milli: 1000
